spring:
    datasource:
        url: jdbc:h2:file:./data/mybd
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            generate-ddl: false
            ddl-auto: update
        properties:
            database-platform: org.hibernate.dialect.H2Dialect
            format-sql: true
            show-sql: true
        h2:
            console:
                enabled: true


